### ISSUE TITLE
Abandoned?

### ISSUE THREAD

**Issue by leandro-lucarella-frequenz** [michalc/aiofastforward#18]
This seems like a good library, but it seems it didn't receive any attention for at least 2 years judging from the open issues and PR.

Is it abandoned? Is it still usable as of today (Python 3.11)?

**Comment by michalc** [comment]
Abandoned is strong... but I think certainly forgotten about for a while.

Will see how it behaves on Python 3.11

**Comment by michalc** [comment]
Test pass on Python 3.11, so I'm going to say yes - just as usable now as it was a few years back.
